### ISSUE TITLE
Does it accept grammars with epsilon?

### ISSUE THREAD

**Issue by megablazikenabhishek** [Vipul97/slr-parser#1]
Does it accept grammars with epsilon? If yes, then how do I input it?

**Comment by Mihan786Chistie** [comment]
I think for epsilon we need to use ^

**Comment by Vipul97** [comment]
@megablazikenabhishek Yes it does accept grammars with epsilon using the `^` symbol - I've mentioned it under the Grammar Syntax section of the README: `^` is treated as the null symbol.
